-- AlterTable
ALTER TABLE `product` MODIFY `ImgUrls` VARCHAR(191) NULL,
    MODIFY `priceDef` INTEGER NOT NULL DEFAULT 0,
    MODIFY `priceNDS` INTEGER NOT NULL DEFAULT 0,
    MODIFY `inStock` INTEGER NOT NULL DEFAULT 0,
    MODIFY `min` INTEGER NOT NULL DEFAULT 0,
    MODIFY `max` INTEGER NOT NULL DEFAULT 0;
